# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems:             [jekyll-paginate, redcarpet]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Rosie on Rails
tagline:          'a Jekyll blog'
description:      'Learning to code, with a side of vintage style.  My name is actually Jessica.'
url:              http://rosieonrails.com
baseurl:          ''

author:
  name:           'Jessica Wray'
  url:            https://twitter.com/jessicaswray

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jessicashannon/jessicashannon.github.io
